hostname: thiccpad
timezone: Europe/Stockholm
country: Sweden
locales:
  - en_US
  - sv_SE

initramfs_hooks:
  - base
  - systemd
  - autodetect
  - keyboard
  - sd-vconsole
  - modconf
  - block
  - sd-encrypt
  - filesystems
  - fsck

packages:
  - arch-wiki-lite
  - coreutils
  - dialog
  - glances
  - linux-firmware
  - lsof
  - moreutils
  - rsync
  - sysstat
  - wpa_supplicant
  - links
  - lynx

# File name for encryption key used by dmcrypt to encrypt non-root
# partitions. The key is stored on encrypted root partition which is unlocked
# with a password.
luks_key_name: luks.key
